### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SudoR2spr** [AdibNikjou/MusicDownloader-Telegram-Bot#5]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from run import Bot
  File "C:\Users\WOODcraft\Desktop\text\op\Vinod Pal vps 14.11.2022\0 spotyfY m
usic bot\MusicDownloader-Telegram-Bot-master\MusicDownloader-Telegram-Bot-master
\run\__init__.py", line 7, in <module>
    from .buttons import Buttons
  File "C:\Users\WOODcraft\Desktop\text\op\Vinod Pal vps 14.11.2022\0 spotyfY m
usic bot\MusicDownloader-Telegram-Bot-master\MusicDownloader-Telegram-Bot-master
\run\buttons.py", line 49
    match mode:
             ^
SyntaxError: invalid syntax

**Comment by AdibNikjou** [comment]
Thank you for reporting this issue.
The error you're encountering is due to the use of the `match` statement in the `buttons.py` file. This feature was introduced in Python 3.10, and it seems you might be using an earlier version.

To resolve this, you have two options:

1. Upgrade your Python installation to version 3.10 or later.
2. If upgrading isn't possible, I can modify the code to use traditional if-elif-else statements instead of the `match` statement.

**Comment by AdibNikjou** [comment]
You can download the modified `buttons.py` file right here :
         [buttons.zip](https://github.com/user-attachments/files/16762543/buttons.zip)
This should resolve the SyntaxError you were experiencing.
Let me know if this works for you.
